import "./global.css";

export const metadata = {
  title: {
    default: "Next.js 14 tutorial",
    template: "%s | Next.js 14",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="h-screen flex flex-col items-center">
        <header className="bg-gray-200 flex self-stretch justify-center p-6">
          Header
        </header>
        <main className="flex items-center justify-center h-screen">
          {children}
        </main>
        <footer className="bg-gray-200 flex self-stretch justify-center p-6">
          Footer
        </footer>
      </body>
    </html>
  );
}
